### PR TITLE
Specs file for Archivematica

### PR DESCRIPTION
**Pull request by scollazo**
* Same filesystem hierarchy than ubuntu one
* Needs epel-release package installed (nginx):
	yum install -y epel-release

### CODE REVIEW

**Comment by sevein** [comment]
gunicorn is now in production.txt!

**Comment by sevein** [comment]
Do you want to discuss the directory organization? I was thinking on something aligned with #1 where each package is contained into its own folder where related files like init scripts, patches, etc could exist, e.g. `rpm/siegfried/{Dockerfile,spec,...}` - does that make sense?

**Comment by scollazo** [comment]
* Added specs for archivematica-common, archivematica-mcp-client and archivematica-mcp-server, 
* Updated descriptions
* Added some dependencies

**Comment by scollazo** [comment]
* Services are not enabled by default  in centos, they should be enabled one by one using systemctl
* There are some conflicts between default configurations of nginx and apache, both use port 80.

**Comment by sevein** [comment]
Bringing this to a halt. Upcoming pull requests are going to cover smaller units of work, likely starting with the storage service.

**Pull request closed without merging**
