### PR TITLE
Update packaging for storage-service 0.8

### PR DESCRIPTION
**Pull request by scollazo**
- Downloads python dependencies on-the-fly, so we don't need to push binary packages to git
- If no -p option (no ppa), runs a binary build

### CODE REVIEW

**Comment by sevein** [comment]
CC @hakamine - this is your are of expertise :)

**Comment by hakamine** [comment]
I think some changes in this PR are reverting changes here: https://github.com/artefactual-labs/am-packbuild/commit/385fece918366c28a2725bcf41a9593bce587d22
We tried before to download with pip but broke in launchpad so we ended with this workaround of putting the tarballs in the repo. Aren't the changes in this PR breaking launchpad building? 
(I guess that if we decide to not use launchpad as I hope we do someday we won't have these problems anyway, but for now ....)

**Comment by sevein** [comment]
It'd be nice to keep compatibility with launchpad because that's still our release channel for 1.4 packages but we're hoping to move 1.5+ to our own repo: packages.archivematica.org. @scollazo, may be a good idea to keep these files around for now?

**Comment by scollazo** [comment]
I'm not well versed on launchpad, but the package we send to them to be built, has the same contents than before. The difference is that previously, the .zip files were copied from this repo, and now they are obtained with pip each time that packbuild.py is run.

**Comment by scollazo** [comment]
The changes to add pip ( >= 8 , as that's the one that provides the _download_ option ) are mean to be run by packbuild.py , so instead of copying files, they are downloaded and put in place.

I tried building binary packages for stable/1.4.x and stable/1.5.x without issues.

**Comment by sevein** [comment]
If you are planning to require a specific version of `pip` I would suggest to add a `requirements.txt` file with that constraint and a check in the code, something like the following will do it:

```python
#!/usr/bin/env python2

from distutils.version import LooseVersion
import logging
import sys

import pip


logging.basicConfig(format='%(levelname)s: %(message)s', level=logging.DEBUG)

PIP_MIN_VERSION = '8.0.0'


if __name__ == "__main__":
    if LooseVersion(pip.__version__) < LooseVersion(PIP_MIN_VERSION):
        logging.error('pip version required not met, we need >=%s and you have %s', PIP_MIN_VERSION, pip.__version__)
        sys.exit(1)
```

**Comment by hakamine** [comment]
:+1:

**Comment by scollazo** [comment]
This PR has been superseed by #36

**Pull request closed without merging**
