### PR TITLE
Don't start mcp-s until mysql is running

### PR DESCRIPTION
**Pull request by scollazo**
Closes artefactual/archivematica#953

### CODE REVIEW

**Comment by jpellman** [comment]
This looks reasonable to me.  The only thing I'd check would be if the mysql/percona packages make a symlink to the mysql.service unit file for compatibility reasons.  If they do, it might make more sense to have both Ubuntu/CentOS unit files use 'mysql.service'.

**Comment by scollazo** [comment]
CentOS uses mariadb, and the service is called mariadb.service

For percona, my tests shown that they use mysql.service, so the ubuntu script will work.

**Comment by sevein** [comment]
> CentOS uses mariadb, and the service is called mariadb.service

So there is no `mysql.service` symlink in that package?

**Comment by jpellman** [comment]
I don't think that there is, which is kinda of strange because you'd think someone would have thought about that, but the CentOS maintainers probably figure that people will only use their packages to install a MySQL/MariaDB server and that any third-party repositories will also take into account their use of `mariadb.service` instead of `mysql.service`.

**Comment by jpellman** [comment]
The more I think about it, I'm not entirely sure how the symlink would work with systemd, since if there are two unit files for MySQL (one a symlink and one not), there's nothing to stop systemd from trying to load both at the same time, which could lead to some nasty side effects.  I'm not entirely sure systemd supports multiple names for services.  At any rate, the proposed pull request should work and looks good to me.

**Comment by sevein** [comment]
@jpellman cool, thanks for investing your time in this!

**Pull request merged**
